### ISSUE TITLE
PANDORA dataset application 

### ISSUE THREAD

**Issue by Nikol-coder** [IamJunhaHwang/Papers#1]
Hello, I recently read the paper "PANDORA Talks: Personality and Demographics on Reddit" and was very interested in the MBTI personality prediction in it. However, I have submitted the application form for the PANDORA data set on their official website a week ago. I only use this data set for academic purposes with sufficient reasons, but I still have not received permission up to now. Can you share the PANDORA dataset directly? I use it for academic purposes only, please...

**Comment by IamJunhaHwang** [comment]
Hi, I did not request the data from the authors. I'm sorry that I couldn't be of help to you.
